-
  hosts: all

  tasks:
    - shell: curl -sL https://deb.nodesource.com/setup_0.12 | bash -

    - name: install dependencies
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
      - nodejs
      - phantomjs
      - g++
      - build-essential

    - npm: name={{ item }} state=latest global=yes
      with_items:
      - gulp
      - bower
      - mocha
